# Site settings
title: Nathanael van den Berg
email: your.email@example.tld
#description: >-
 # A portfolio showcasing my game design projects, interactive experiences,
 # and creative journey in the gaming industry.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amanatil.github.io" # the base hostname & protocol for your site
#twitter_username: yourusername
github_username: amanatil
linkedin_username: nathan-van-den-berg-9616b7186

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/
  games:
    output: true
    permalink: /games/:name/
  photography:
    output: true
    permalink: /photography/:name/

include:
  - _pages
  
# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "games"
    values:
      layout: "game"
  - scope:
      path: ""
      type: "photography"
    values:
      layout: "photo"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - tailwind.config.js
  - src/

# Tailwind CSS
sass:
  sass_dir: _sass
  style: compressed