version: '3.8'

services:
  jekyll:
    build: .
    ports:
      - "4000:4000"   # Jekyll server
      - "35729:35729" # LiveReload
    volumes:
      - .:/app
      - /app/node_modules
      - /app/vendor
      - jekyll_bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --host 0.0.0.0 --livereload --incremental --force_polling

volumes:
  jekyll_bundle:
